### ISSUE TITLE
Moderation page breaks on deployment

### ISSUE THREAD

**Issue by JamsterJava** [CMD-Forum/cmd-forum#23]
Looking at the Vercel logs, this is what's causing the issue:

```
ReferenceError: prisma is not defined
    at u (/var/task/.next/server/app/(general)/c/[community]/moderation/page.js:1:9712)
    at eh (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at Array.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
    at stringify (<anonymous>)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219)
    at eE (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
    at listOnTimeout (node:internal/timers:569:17) {
  digest: '1700241303'
}
```

I'm wondering if this also happens locally and was never noticed.

**Comment by JamsterJava** [comment]
Looking at the moderation page, I found the offending code:

```jsx
import LargeDropdown from "@/app/(general)/ui/components/large_dropdown";
import { CommunityAdministrators } from "@/app/(general)/ui/components/moderation/admin_list";
import { ModlogList } from "@/app/(general)/ui/components/moderation/modlog_list";

export default async function ModerationPage({ params }: { params: { community: string } }) {
    
    const community = await prisma?.community.findUnique({
        where: {
            name: params.community
        },
        select: {
            id: true,
        }
    })

...
```

Prisma isn't imported at all, so it isn't defined. This is an easy fix.

```jsx
import LargeDropdown from "@/app/(general)/ui/components/large_dropdown";
import { CommunityAdministrators } from "@/app/(general)/ui/components/moderation/admin_list";
import { ModlogList } from "@/app/(general)/ui/components/moderation/modlog_list";
import { prisma } from "@/app/(general)/lib/db"; // Import Prisma

export default async function ModerationPage({ params }: { params: { community: string } }) {
    
    const community = await prisma.community.findUnique({ // Remove '?' as it's defined now
        where: {
            name: params.community
        },
        select: {
            id: true,
        }
    })

...
```
